base_url = "https://www.google.com.ua/"

browser_name_chrome = "chrome"
browser_name_firefox = "firefox"

browser_non_supported_message = "{} browser is not supported"
browser_type_error_message = "string_browser_name must be string"
url_type_error_message = "URL must be a string"

assert_element_is_not_displayed_message = "'{}' is not displayed"
assert_element_is_not_enabled_message = "'{}' is not enabled"
assert_difference_in_titles_message = "Difference in titles. Eth: {}; Curr: {}"
assert_url_message = "Curr URL does not contain eth URL. Eth: {}; Curr: {}"
assert_html_of_element_is_not_defined_message = "html of element is not defined"
assert_element_is_not_clickable_message = "Element with locator {} is not clickable"

main_page_id_body = "body"
main_page_tag_img = "img"
main_page_tag_timeout_message = "Element '{}' does not contain the '{}' tag"
main_page_id_searchform = "searchform"
main_page_class_FPdoLc = "FPdoLc"
main_page_name_btnK = "btnK"
main_page_name_btnI = "btnI"
main_page_tag_input = "input"
main_page_inputs_timeout_message = "Inputs are not present"
main_page_input_with_defined_class_is_not_found_assert_message = "Input with defined class is not found"
main_page_attribute_class = "class"
main_page_img_is_not_displayed_assert_message = "Image is not displayed"
main_page_attribute_alt = "alt"
main_page_img_assert_message = "Attribute '{}' of image. Eth: {} Curr: {}"
main_page_input_enabling_assert_message = "Input of searching is not enabled"
main_page_attribute_value = "value"
main_page_difference_in_values_assert_message = "Difference in input's values. Eth: {}; Curr: {}"
main_page_class_UUbT9 = "UUbT9"
main_page_element_with_class_is_not_visible_assert_message = "Element with class {} is not visible"

class_is_not_present_timeout_message = "Element with class {} is not present"
id_is_not_present_timeout_message = "Element with ID: {} is not present in DOM"

search_page_class_srg = "srg"
search_page_id_foot = "foot"
search_page_tag_tbody = "tbody"
search_page_tag_is_not_defined_timeout_message = "Element with tag {} is not defined"
search_page_class_g = "g"
search_page_elements_with_class_are_not_visible_timeout_message = "Elements with class {} are not visible"
search_page_tag_td = "td"
search_page_elements_with_tag_are_not_present_timeout_message = "Elements with tag {} are not present"
search_page_attribute_class = "class"
search_page_eth_attribute_class = "cur"
search_page_difference_in_pages_assert_message = "Difference in pages numbers. Eth: {}; Curr: {}"
search_page_results_are_not_found_assert_message = "Results of searching are not found"
search_page_the_previous_srg_is_attached = "The previous '{}' is attached to the DOM"

test_google_string_eth_title = "TEST - Пошук Google"
test_google_string_defined_page = "2"
